apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-demo
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: api:latest
        imagePullPolicy: IfNotPresent
        name: api
        env:
          - name: RANDOM_SERVICE_URL
            value: "http://random-service"
        ports:
          - containerPort: 80
        resources:
            limits:
              memory: '128Mi'
              cpu: '200m'