apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-demo
  name: client
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: client:latest
          imagePullPolicy: IfNotPresent
          name: client
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '128Mi'
              cpu: '200m'
