apiVersion: v1
kind: Service
metadata:
  name: client-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:
    app: client
